### ISSUE TITLE
能否做一个详细点的配置说明

### ISSUE THREAD

**Issue by djkcyl** [MeowCat-Studio/message-forwarding#25]
研究了半天不知道怎么用，希望能给个完整的mc端和qq端的对接方法

**Comment by Itsusinn** [comment]
https://github.com/MeowCat-Studio/message-forwarding/issues/2
在写了在写了

**Comment by djkcyl** [comment]
好的，还有就是这个插件里面的host和port里面填的是什么啊

**Comment by Itsusinn** [comment]
> 好的，还有就是这个插件里面的host和port里面填的是什么啊
> 顺便问一下，这个有没有移植到forge的计划啊

host和port是一个消息派发器
https://github.com/MeowCat-Studio/message-dispatcher
你可以简单地理解为mc收到消息后先将消息上报至派发器，再由派发器发送到qq，反之亦然。
(这一设计的初衷是为了支持tg和dc，用户并不需要配置这个派发器)

关于forge，据我了解应该没有服务端支持了forge而不支持bukkit的,
如果存在这样的服务端的话，会移植到forge.

**Comment by djkcyl** [comment]
> > 好的，还有就是这个插件里面的host和port里面填的是什么啊
> > 顺便问一下，这个有没有移植到forge的计划啊
> 
> host和port是一个消息派发器(目前来说保持默认值就好)
> https://github.com/MeowCat-Studio/message-dispatcher
> 你可以简单地理解为mc收到消息后先将消息上报至派发器，再由派发器发送到qq，反之亦然。
> (这一设计的初衷是为了支持tg和dc，用户并不需要配置这个派发器)
> 
> 关于forge，据我了解应该没有服务端支持了forge而不支持bukkit的,
> 如果存在这样的服务端的话，会移植到forge.

也就是说现在host和port是一个建立在公网的消息派发服务端
forge的话因为我是开forge整合包服的，用的是官方的forge端，没有用那种支持bukkit也支持forge的服务端，所以想问一下这个

**Comment by Itsusinn** [comment]
> > > 好的，还有就是这个插件里面的host和port里面填的是什么啊
> > > 顺便问一下，这个有没有移植到forge的计划啊
> > 
> > 
> > host和port是一个消息派发器(目前来说保持默认值就好)
> > https://github.com/MeowCat-Studio/message-dispatcher
> > 你可以简单地理解为mc收到消息后先将消息上报至派发器，再由派发器发送到qq，反之亦然。
> > (这一设计的初衷是为了支持tg和dc，用户并不需要配置这个派发器)
> > 关于forge，据我了解应该没有服务端支持了forge而不支持bukkit的,
> > 如果存在这样的服务端的话，会移植到forge.
> 
> 也就是说现在host和port是一个建立在公网的消息派发服务端
> forge的话因为我是开forge整合包服的，用的是官方的forge端，没有用那种支持bukkit也支持forge的服务端，所以想问一下这个

https://github.com/IzzelAliz/Arclight
or
https://github.com/Mohist-Community/Mohist

**Comment by djkcyl** [comment]
> > > > 好的，还有就是这个插件里面的host和port里面填的是什么啊
> > > > 顺便问一下，这个有没有移植到forge的计划啊
> > > 
> > > 
> > > host和port是一个消息派发器(目前来说保持默认值就好)
> > > https://github.com/MeowCat-Studio/message-dispatcher
> > > 你可以简单地理解为mc收到消息后先将消息上报至派发器，再由派发器发送到qq，反之亦然。
> > > (这一设计的初衷是为了支持tg和dc，用户并不需要配置这个派发器)
> > > 关于forge，据我了解应该没有服务端支持了forge而不支持bukkit的,
> > > 如果存在这样的服务端的话，会移植到forge.
> > 
> > 
> > 也就是说现在host和port是一个建立在公网的消息派发服务端
> > forge的话因为我是开forge整合包服的，用的是官方的forge端，没有用那种支持bukkit也支持forge的服务端，所以想问一下这个
> 
> https://github.com/IzzelAliz/Arclight
> or
> https://github.com/Mohist-Community/Mohist

Arclight和Mohist这类服务端我尝试过，因为mod兼容性问题，curseforge的大型整合包的官方服务器开不起来。

**Comment by Itsusinn** [comment]
(

**Comment by djkcyl** [comment]
因为一些asm的魔改会导致这类服务端崩溃

**Comment by Itsusinn** [comment]
https://github.com/MeowCat-Studio/message-forwarding/issues/26

**Comment by djkcyl** [comment]
对了，这个消息派发器我是可以自己编译了开在本地的对吧

**Comment by Itsusinn** [comment]
> 对了，这个消息派发器我是可以自己编译了开在本地的对吧

可以是可以，但是十分没必要

**Comment by djkcyl** [comment]
> > 对了，这个消息派发器我是可以自己编译了开在本地的对吧
> 
> 可以是可以，但是十分没必要

毕竟自己开也能减轻点你们服务器的压力，这个其实可以加在wiki里，有条件的自己开，没条件的就用你们提供的现成派发器

**Comment by Itsusinn** [comment]
目前压力小的很（　我跑在学生机上
wiki没准会出个部署

**Comment by djkcyl** [comment]
> 目前压力小的很（　我跑在学生机上
> wiki没准会出个部署

那好吧

**Comment by Itsusinn** [comment]
已完成wiki的编写,入仍有问题可提交至本项目的discussions
https://github.com/MeowCat-Studio/message-forwarding/discussions
